//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class PositionMsg : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/Position";
        public override string RosMessageName => k_RosMessageName;

        public string name;
        public double[] joints;
        public RPYMsg rpy;
        public Geometry.PointMsg point;
        public Geometry.QuaternionMsg quaternion;

        public PositionMsg()
        {
            this.name = "";
            this.joints = new double[0];
            this.rpy = new RPYMsg();
            this.point = new Geometry.PointMsg();
            this.quaternion = new Geometry.QuaternionMsg();
        }

        public PositionMsg(string name, double[] joints, RPYMsg rpy, Geometry.PointMsg point, Geometry.QuaternionMsg quaternion)
        {
            this.name = name;
            this.joints = joints;
            this.rpy = rpy;
            this.point = point;
            this.quaternion = quaternion;
        }

        public static PositionMsg Deserialize(MessageDeserializer deserializer) => new PositionMsg(deserializer);

        private PositionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
            deserializer.Read(out this.joints, sizeof(double), deserializer.ReadLength());
            this.rpy = RPYMsg.Deserialize(deserializer);
            this.point = Geometry.PointMsg.Deserialize(deserializer);
            this.quaternion = Geometry.QuaternionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
            serializer.WriteLength(this.joints);
            serializer.Write(this.joints);
            serializer.Write(this.rpy);
            serializer.Write(this.point);
            serializer.Write(this.quaternion);
        }

        public override string ToString()
        {
            return "PositionMsg: " +
            "\nname: " + name.ToString() +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\nrpy: " + rpy.ToString() +
            "\npoint: " + point.ToString() +
            "\nquaternion: " + quaternion.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
