//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ProcessStateMsg : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ProcessState";
        public override string RosMessageName => k_RosMessageName;

        public string[] name;
        public bool[] is_active;

        public ProcessStateMsg()
        {
            this.name = new string[0];
            this.is_active = new bool[0];
        }

        public ProcessStateMsg(string[] name, bool[] is_active)
        {
            this.name = name;
            this.is_active = is_active;
        }

        public static ProcessStateMsg Deserialize(MessageDeserializer deserializer) => new ProcessStateMsg(deserializer);

        private ProcessStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name, deserializer.ReadLength());
            deserializer.Read(out this.is_active, sizeof(bool), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.name);
            serializer.Write(this.name);
            serializer.WriteLength(this.is_active);
            serializer.Write(this.is_active);
        }

        public override string ToString()
        {
            return "ProcessStateMsg: " +
            "\nname: " + System.String.Join(", ", name.ToList()) +
            "\nis_active: " + System.String.Join(", ", is_active.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
