//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class RPYMsg : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/RPY";
        public override string RosMessageName => k_RosMessageName;

        //  roll, pitch and yaw
        public double roll;
        public double pitch;
        public double yaw;

        public RPYMsg()
        {
            this.roll = 0.0;
            this.pitch = 0.0;
            this.yaw = 0.0;
        }

        public RPYMsg(double roll, double pitch, double yaw)
        {
            this.roll = roll;
            this.pitch = pitch;
            this.yaw = yaw;
        }

        public static RPYMsg Deserialize(MessageDeserializer deserializer) => new RPYMsg(deserializer);

        private RPYMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.roll);
            deserializer.Read(out this.pitch);
            deserializer.Read(out this.yaw);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.roll);
            serializer.Write(this.pitch);
            serializer.Write(this.yaw);
        }

        public override string ToString()
        {
            return "RPYMsg: " +
            "\nroll: " + roll.ToString() +
            "\npitch: " + pitch.ToString() +
            "\nyaw: " + yaw.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
