//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class SequenceAutorunStatusMsg : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/SequenceAutorunStatus";
        public override string RosMessageName => k_RosMessageName;

        public bool enabled;
        public int mode;
        public int[] sequence_ids;

        public SequenceAutorunStatusMsg()
        {
            this.enabled = false;
            this.mode = 0;
            this.sequence_ids = new int[0];
        }

        public SequenceAutorunStatusMsg(bool enabled, int mode, int[] sequence_ids)
        {
            this.enabled = enabled;
            this.mode = mode;
            this.sequence_ids = sequence_ids;
        }

        public static SequenceAutorunStatusMsg Deserialize(MessageDeserializer deserializer) => new SequenceAutorunStatusMsg(deserializer);

        private SequenceAutorunStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enabled);
            deserializer.Read(out this.mode);
            deserializer.Read(out this.sequence_ids, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enabled);
            serializer.Write(this.mode);
            serializer.WriteLength(this.sequence_ids);
            serializer.Write(this.sequence_ids);
        }

        public override string ToString()
        {
            return "SequenceAutorunStatusMsg: " +
            "\nenabled: " + enabled.ToString() +
            "\nmode: " + mode.ToString() +
            "\nsequence_ids: " + System.String.Join(", ", sequence_ids.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
