//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class SequenceMsg : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/Sequence";
        public override string RosMessageName => k_RosMessageName;

        public int id;
        public string name;
        public string description;
        public int created;
        public int updated;
        public string blockly_xml;
        public string python_code;

        public SequenceMsg()
        {
            this.id = 0;
            this.name = "";
            this.description = "";
            this.created = 0;
            this.updated = 0;
            this.blockly_xml = "";
            this.python_code = "";
        }

        public SequenceMsg(int id, string name, string description, int created, int updated, string blockly_xml, string python_code)
        {
            this.id = id;
            this.name = name;
            this.description = description;
            this.created = created;
            this.updated = updated;
            this.blockly_xml = blockly_xml;
            this.python_code = python_code;
        }

        public static SequenceMsg Deserialize(MessageDeserializer deserializer) => new SequenceMsg(deserializer);

        private SequenceMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.name);
            deserializer.Read(out this.description);
            deserializer.Read(out this.created);
            deserializer.Read(out this.updated);
            deserializer.Read(out this.blockly_xml);
            deserializer.Read(out this.python_code);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.name);
            serializer.Write(this.description);
            serializer.Write(this.created);
            serializer.Write(this.updated);
            serializer.Write(this.blockly_xml);
            serializer.Write(this.python_code);
        }

        public override string ToString()
        {
            return "SequenceMsg: " +
            "\nid: " + id.ToString() +
            "\nname: " + name.ToString() +
            "\ndescription: " + description.ToString() +
            "\ncreated: " + created.ToString() +
            "\nupdated: " + updated.ToString() +
            "\nblockly_xml: " + blockly_xml.ToString() +
            "\npython_code: " + python_code.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
