//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ShiftPoseMsg : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ShiftPose";
        public override string RosMessageName => k_RosMessageName;

        public int axis_number;
        public double value;

        public ShiftPoseMsg()
        {
            this.axis_number = 0;
            this.value = 0.0;
        }

        public ShiftPoseMsg(int axis_number, double value)
        {
            this.axis_number = axis_number;
            this.value = value;
        }

        public static ShiftPoseMsg Deserialize(MessageDeserializer deserializer) => new ShiftPoseMsg(deserializer);

        private ShiftPoseMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.axis_number);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.axis_number);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "ShiftPoseMsg: " +
            "\naxis_number: " + axis_number.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
