//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class SoftwareVersionMsg : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/SoftwareVersion";
        public override string RosMessageName => k_RosMessageName;

        public string rpi_image_version;
        public string ros_niryo_one_version;
        public string[] motor_names;
        public string[] stepper_firmware_versions;

        public SoftwareVersionMsg()
        {
            this.rpi_image_version = "";
            this.ros_niryo_one_version = "";
            this.motor_names = new string[0];
            this.stepper_firmware_versions = new string[0];
        }

        public SoftwareVersionMsg(string rpi_image_version, string ros_niryo_one_version, string[] motor_names, string[] stepper_firmware_versions)
        {
            this.rpi_image_version = rpi_image_version;
            this.ros_niryo_one_version = ros_niryo_one_version;
            this.motor_names = motor_names;
            this.stepper_firmware_versions = stepper_firmware_versions;
        }

        public static SoftwareVersionMsg Deserialize(MessageDeserializer deserializer) => new SoftwareVersionMsg(deserializer);

        private SoftwareVersionMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.rpi_image_version);
            deserializer.Read(out this.ros_niryo_one_version);
            deserializer.Read(out this.motor_names, deserializer.ReadLength());
            deserializer.Read(out this.stepper_firmware_versions, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rpi_image_version);
            serializer.Write(this.ros_niryo_one_version);
            serializer.WriteLength(this.motor_names);
            serializer.Write(this.motor_names);
            serializer.WriteLength(this.stepper_firmware_versions);
            serializer.Write(this.stepper_firmware_versions);
        }

        public override string ToString()
        {
            return "SoftwareVersionMsg: " +
            "\nrpi_image_version: " + rpi_image_version.ToString() +
            "\nros_niryo_one_version: " + ros_niryo_one_version.ToString() +
            "\nmotor_names: " + System.String.Join(", ", motor_names.ToList()) +
            "\nstepper_firmware_versions: " + System.String.Join(", ", stepper_firmware_versions.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
