//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ChangeHardwareVersionRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ChangeHardwareVersion";
        public override string RosMessageName => k_RosMessageName;

        public int old_version;
        public int new_version;

        public ChangeHardwareVersionRequest()
        {
            this.old_version = 0;
            this.new_version = 0;
        }

        public ChangeHardwareVersionRequest(int old_version, int new_version)
        {
            this.old_version = old_version;
            this.new_version = new_version;
        }

        public static ChangeHardwareVersionRequest Deserialize(MessageDeserializer deserializer) => new ChangeHardwareVersionRequest(deserializer);

        private ChangeHardwareVersionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.old_version);
            deserializer.Read(out this.new_version);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.old_version);
            serializer.Write(this.new_version);
        }

        public override string ToString()
        {
            return "ChangeHardwareVersionRequest: " +
            "\nold_version: " + old_version.ToString() +
            "\nnew_version: " + new_version.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
