//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ChangeMotorConfigRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ChangeMotorConfig";
        public override string RosMessageName => k_RosMessageName;

        public int[] can_required_motor_id_list;
        public int[] dxl_required_motor_id_list;

        public ChangeMotorConfigRequest()
        {
            this.can_required_motor_id_list = new int[0];
            this.dxl_required_motor_id_list = new int[0];
        }

        public ChangeMotorConfigRequest(int[] can_required_motor_id_list, int[] dxl_required_motor_id_list)
        {
            this.can_required_motor_id_list = can_required_motor_id_list;
            this.dxl_required_motor_id_list = dxl_required_motor_id_list;
        }

        public static ChangeMotorConfigRequest Deserialize(MessageDeserializer deserializer) => new ChangeMotorConfigRequest(deserializer);

        private ChangeMotorConfigRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.can_required_motor_id_list, sizeof(int), deserializer.ReadLength());
            deserializer.Read(out this.dxl_required_motor_id_list, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.can_required_motor_id_list);
            serializer.Write(this.can_required_motor_id_list);
            serializer.WriteLength(this.dxl_required_motor_id_list);
            serializer.Write(this.dxl_required_motor_id_list);
        }

        public override string ToString()
        {
            return "ChangeMotorConfigRequest: " +
            "\ncan_required_motor_id_list: " + System.String.Join(", ", can_required_motor_id_list.ToList()) +
            "\ndxl_required_motor_id_list: " + System.String.Join(", ", dxl_required_motor_id_list.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
