//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class DebugMarkersResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/DebugMarkers";
        public override string RosMessageName => k_RosMessageName;

        public bool markers_detected;
        public Sensor.CompressedImageMsg img;

        public DebugMarkersResponse()
        {
            this.markers_detected = false;
            this.img = new Sensor.CompressedImageMsg();
        }

        public DebugMarkersResponse(bool markers_detected, Sensor.CompressedImageMsg img)
        {
            this.markers_detected = markers_detected;
            this.img = img;
        }

        public static DebugMarkersResponse Deserialize(MessageDeserializer deserializer) => new DebugMarkersResponse(deserializer);

        private DebugMarkersResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.markers_detected);
            this.img = Sensor.CompressedImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.markers_detected);
            serializer.Write(this.img);
        }

        public override string ToString()
        {
            return "DebugMarkersResponse: " +
            "\nmarkers_detected: " + markers_detected.ToString() +
            "\nimg: " + img.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
