//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class DebugColorDetectionRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/DebugColorDetection";
        public override string RosMessageName => k_RosMessageName;

        public string color;

        public DebugColorDetectionRequest()
        {
            this.color = "";
        }

        public DebugColorDetectionRequest(string color)
        {
            this.color = color;
        }

        public static DebugColorDetectionRequest Deserialize(MessageDeserializer deserializer) => new DebugColorDetectionRequest(deserializer);

        private DebugColorDetectionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.color);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.color);
        }

        public override string ToString()
        {
            return "DebugColorDetectionRequest: " +
            "\ncolor: " + color.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
