//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class DebugMarkersRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/DebugMarkers";
        public override string RosMessageName => k_RosMessageName;


        public DebugMarkersRequest()
        {
        }
        public static DebugMarkersRequest Deserialize(MessageDeserializer deserializer) => new DebugMarkersRequest(deserializer);

        private DebugMarkersRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "DebugMarkersRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
