//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class EditWorkspaceRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/EditWorkspace";
        public override string RosMessageName => k_RosMessageName;

        public const int CREATE = 1;
        public const int REMOVE = -1;
        public int cmd;
        public string name;
        public RobotStateMsg pose_origin;
        public RobotStateMsg pose_1;
        public RobotStateMsg pose_2;
        public RobotStateMsg pose_3;

        public EditWorkspaceRequest()
        {
            this.cmd = 0;
            this.name = "";
            this.pose_origin = new RobotStateMsg();
            this.pose_1 = new RobotStateMsg();
            this.pose_2 = new RobotStateMsg();
            this.pose_3 = new RobotStateMsg();
        }

        public EditWorkspaceRequest(int cmd, string name, RobotStateMsg pose_origin, RobotStateMsg pose_1, RobotStateMsg pose_2, RobotStateMsg pose_3)
        {
            this.cmd = cmd;
            this.name = name;
            this.pose_origin = pose_origin;
            this.pose_1 = pose_1;
            this.pose_2 = pose_2;
            this.pose_3 = pose_3;
        }

        public static EditWorkspaceRequest Deserialize(MessageDeserializer deserializer) => new EditWorkspaceRequest(deserializer);

        private EditWorkspaceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd);
            deserializer.Read(out this.name);
            this.pose_origin = RobotStateMsg.Deserialize(deserializer);
            this.pose_1 = RobotStateMsg.Deserialize(deserializer);
            this.pose_2 = RobotStateMsg.Deserialize(deserializer);
            this.pose_3 = RobotStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd);
            serializer.Write(this.name);
            serializer.Write(this.pose_origin);
            serializer.Write(this.pose_1);
            serializer.Write(this.pose_2);
            serializer.Write(this.pose_3);
        }

        public override string ToString()
        {
            return "EditWorkspaceRequest: " +
            "\ncmd: " + cmd.ToString() +
            "\nname: " + name.ToString() +
            "\npose_origin: " + pose_origin.ToString() +
            "\npose_1: " + pose_1.ToString() +
            "\npose_2: " + pose_2.ToString() +
            "\npose_3: " + pose_3.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
