//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class EditGripRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/EditGrip";
        public override string RosMessageName => k_RosMessageName;

        public const int CREATE = 1;
        public const int REMOVE = -1;
        public int cmd;
        public string name;
        public string workspace;
        public RobotStateMsg robot_pose;

        public EditGripRequest()
        {
            this.cmd = 0;
            this.name = "";
            this.workspace = "";
            this.robot_pose = new RobotStateMsg();
        }

        public EditGripRequest(int cmd, string name, string workspace, RobotStateMsg robot_pose)
        {
            this.cmd = cmd;
            this.name = name;
            this.workspace = workspace;
            this.robot_pose = robot_pose;
        }

        public static EditGripRequest Deserialize(MessageDeserializer deserializer) => new EditGripRequest(deserializer);

        private EditGripRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd);
            deserializer.Read(out this.name);
            deserializer.Read(out this.workspace);
            this.robot_pose = RobotStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd);
            serializer.Write(this.name);
            serializer.Write(this.workspace);
            serializer.Write(this.robot_pose);
        }

        public override string ToString()
        {
            return "EditGripRequest: " +
            "\ncmd: " + cmd.ToString() +
            "\nname: " + name.ToString() +
            "\nworkspace: " + workspace.ToString() +
            "\nrobot_pose: " + robot_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
