//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetCalibrationCamRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetCalibrationCam";
        public override string RosMessageName => k_RosMessageName;

        public Std.EmptyMsg empty;

        public GetCalibrationCamRequest()
        {
            this.empty = new Std.EmptyMsg();
        }

        public GetCalibrationCamRequest(Std.EmptyMsg empty)
        {
            this.empty = empty;
        }

        public static GetCalibrationCamRequest Deserialize(MessageDeserializer deserializer) => new GetCalibrationCamRequest(deserializer);

        private GetCalibrationCamRequest(MessageDeserializer deserializer)
        {
            this.empty = Std.EmptyMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.empty);
        }

        public override string ToString()
        {
            return "GetCalibrationCamRequest: " +
            "\nempty: " + empty.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
