//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetCalibrationCamResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetCalibrationCam";
        public override string RosMessageName => k_RosMessageName;

        public bool is_set;
        public Sensor.CameraInfoMsg camera_info;

        public GetCalibrationCamResponse()
        {
            this.is_set = false;
            this.camera_info = new Sensor.CameraInfoMsg();
        }

        public GetCalibrationCamResponse(bool is_set, Sensor.CameraInfoMsg camera_info)
        {
            this.is_set = is_set;
            this.camera_info = camera_info;
        }

        public static GetCalibrationCamResponse Deserialize(MessageDeserializer deserializer) => new GetCalibrationCamResponse(deserializer);

        private GetCalibrationCamResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_set);
            this.camera_info = Sensor.CameraInfoMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_set);
            serializer.Write(this.camera_info);
        }

        public override string ToString()
        {
            return "GetCalibrationCamResponse: " +
            "\nis_set: " + is_set.ToString() +
            "\ncamera_info: " + camera_info.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
