//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetDigitalIORequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetDigitalIO";
        public override string RosMessageName => k_RosMessageName;

        public int pin;

        public GetDigitalIORequest()
        {
            this.pin = 0;
        }

        public GetDigitalIORequest(int pin)
        {
            this.pin = pin;
        }

        public static GetDigitalIORequest Deserialize(MessageDeserializer deserializer) => new GetDigitalIORequest(deserializer);

        private GetDigitalIORequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pin);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pin);
        }

        public override string ToString()
        {
            return "GetDigitalIORequest: " +
            "\npin: " + pin.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
