//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetDigitalIOResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetDigitalIO";
        public override string RosMessageName => k_RosMessageName;

        public int status;
        public string message;
        public int pin;
        public string name;
        public int mode;
        public int state;

        public GetDigitalIOResponse()
        {
            this.status = 0;
            this.message = "";
            this.pin = 0;
            this.name = "";
            this.mode = 0;
            this.state = 0;
        }

        public GetDigitalIOResponse(int status, string message, int pin, string name, int mode, int state)
        {
            this.status = status;
            this.message = message;
            this.pin = pin;
            this.name = name;
            this.mode = mode;
            this.state = state;
        }

        public static GetDigitalIOResponse Deserialize(MessageDeserializer deserializer) => new GetDigitalIOResponse(deserializer);

        private GetDigitalIOResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.message);
            deserializer.Read(out this.pin);
            deserializer.Read(out this.name);
            deserializer.Read(out this.mode);
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.message);
            serializer.Write(this.pin);
            serializer.Write(this.name);
            serializer.Write(this.mode);
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "GetDigitalIOResponse: " +
            "\nstatus: " + status.ToString() +
            "\nmessage: " + message.ToString() +
            "\npin: " + pin.ToString() +
            "\nname: " + name.ToString() +
            "\nmode: " + mode.ToString() +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
