//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetIntResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetInt";
        public override string RosMessageName => k_RosMessageName;

        public int value;

        public GetIntResponse()
        {
            this.value = 0;
        }

        public GetIntResponse(int value)
        {
            this.value = value;
        }

        public static GetIntResponse Deserialize(MessageDeserializer deserializer) => new GetIntResponse(deserializer);

        private GetIntResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "GetIntResponse: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
