//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetSequenceListRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetSequenceList";
        public override string RosMessageName => k_RosMessageName;

        public bool info_header_only;

        public GetSequenceListRequest()
        {
            this.info_header_only = false;
        }

        public GetSequenceListRequest(bool info_header_only)
        {
            this.info_header_only = info_header_only;
        }

        public static GetSequenceListRequest Deserialize(MessageDeserializer deserializer) => new GetSequenceListRequest(deserializer);

        private GetSequenceListRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.info_header_only);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.info_header_only);
        }

        public override string ToString()
        {
            return "GetSequenceListRequest: " +
            "\ninfo_header_only: " + info_header_only.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
