//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetTrajectoryListResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetTrajectoryList";
        public override string RosMessageName => k_RosMessageName;

        public TrajectoryMsg[] trajectories;

        public GetTrajectoryListResponse()
        {
            this.trajectories = new TrajectoryMsg[0];
        }

        public GetTrajectoryListResponse(TrajectoryMsg[] trajectories)
        {
            this.trajectories = trajectories;
        }

        public static GetTrajectoryListResponse Deserialize(MessageDeserializer deserializer) => new GetTrajectoryListResponse(deserializer);

        private GetTrajectoryListResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.trajectories, TrajectoryMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.trajectories);
            serializer.Write(this.trajectories);
        }

        public override string ToString()
        {
            return "GetTrajectoryListResponse: " +
            "\ntrajectories: " + System.String.Join(", ", trajectories.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
