//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetTargetPoseResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetTargetPose";
        public override string RosMessageName => k_RosMessageName;

        public int status;
        public string message;
        public RobotStateMsg target_pose;

        public GetTargetPoseResponse()
        {
            this.status = 0;
            this.message = "";
            this.target_pose = new RobotStateMsg();
        }

        public GetTargetPoseResponse(int status, string message, RobotStateMsg target_pose)
        {
            this.status = status;
            this.message = message;
            this.target_pose = target_pose;
        }

        public static GetTargetPoseResponse Deserialize(MessageDeserializer deserializer) => new GetTargetPoseResponse(deserializer);

        private GetTargetPoseResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.message);
            this.target_pose = RobotStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.message);
            serializer.Write(this.target_pose);
        }

        public override string ToString()
        {
            return "GetTargetPoseResponse: " +
            "\nstatus: " + status.ToString() +
            "\nmessage: " + message.ToString() +
            "\ntarget_pose: " + target_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
