//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetWorkspaceRatioResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetWorkspaceRatio";
        public override string RosMessageName => k_RosMessageName;

        public int status;
        public string message;
        public float ratio;
        //  width/height

        public GetWorkspaceRatioResponse()
        {
            this.status = 0;
            this.message = "";
            this.ratio = 0.0f;
        }

        public GetWorkspaceRatioResponse(int status, string message, float ratio)
        {
            this.status = status;
            this.message = message;
            this.ratio = ratio;
        }

        public static GetWorkspaceRatioResponse Deserialize(MessageDeserializer deserializer) => new GetWorkspaceRatioResponse(deserializer);

        private GetWorkspaceRatioResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.message);
            deserializer.Read(out this.ratio);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.message);
            serializer.Write(this.ratio);
        }

        public override string ToString()
        {
            return "GetWorkspaceRatioResponse: " +
            "\nstatus: " + status.ToString() +
            "\nmessage: " + message.ToString() +
            "\nratio: " + ratio.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
