//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetWorkspaceRobotPosesRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetWorkspaceRobotPoses";
        public override string RosMessageName => k_RosMessageName;

        public string workspace;

        public GetWorkspaceRobotPosesRequest()
        {
            this.workspace = "";
        }

        public GetWorkspaceRobotPosesRequest(string workspace)
        {
            this.workspace = workspace;
        }

        public static GetWorkspaceRobotPosesRequest Deserialize(MessageDeserializer deserializer) => new GetWorkspaceRobotPosesRequest(deserializer);

        private GetWorkspaceRobotPosesRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.workspace);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.workspace);
        }

        public override string ToString()
        {
            return "GetWorkspaceRobotPosesRequest: " +
            "\nworkspace: " + workspace.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
