//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetWorkspaceRobotPosesResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetWorkspaceRobotPoses";
        public override string RosMessageName => k_RosMessageName;

        public int status;
        public string message;
        public RobotStateMsg pose_origin;
        public RobotStateMsg pose_1;
        public RobotStateMsg pose_2;
        public RobotStateMsg pose_3;

        public GetWorkspaceRobotPosesResponse()
        {
            this.status = 0;
            this.message = "";
            this.pose_origin = new RobotStateMsg();
            this.pose_1 = new RobotStateMsg();
            this.pose_2 = new RobotStateMsg();
            this.pose_3 = new RobotStateMsg();
        }

        public GetWorkspaceRobotPosesResponse(int status, string message, RobotStateMsg pose_origin, RobotStateMsg pose_1, RobotStateMsg pose_2, RobotStateMsg pose_3)
        {
            this.status = status;
            this.message = message;
            this.pose_origin = pose_origin;
            this.pose_1 = pose_1;
            this.pose_2 = pose_2;
            this.pose_3 = pose_3;
        }

        public static GetWorkspaceRobotPosesResponse Deserialize(MessageDeserializer deserializer) => new GetWorkspaceRobotPosesResponse(deserializer);

        private GetWorkspaceRobotPosesResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.message);
            this.pose_origin = RobotStateMsg.Deserialize(deserializer);
            this.pose_1 = RobotStateMsg.Deserialize(deserializer);
            this.pose_2 = RobotStateMsg.Deserialize(deserializer);
            this.pose_3 = RobotStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.message);
            serializer.Write(this.pose_origin);
            serializer.Write(this.pose_1);
            serializer.Write(this.pose_2);
            serializer.Write(this.pose_3);
        }

        public override string ToString()
        {
            return "GetWorkspaceRobotPosesResponse: " +
            "\nstatus: " + status.ToString() +
            "\nmessage: " + message.ToString() +
            "\npose_origin: " + pose_origin.ToString() +
            "\npose_1: " + pose_1.ToString() +
            "\npose_2: " + pose_2.ToString() +
            "\npose_3: " + pose_3.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
