//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class GetWorkspaceListRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/GetWorkspaceList";
        public override string RosMessageName => k_RosMessageName;


        public GetWorkspaceListRequest()
        {
        }
        public static GetWorkspaceListRequest Deserialize(MessageDeserializer deserializer) => new GetWorkspaceListRequest(deserializer);

        private GetWorkspaceListRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetWorkspaceListRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
