//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ManageSequenceRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ManageSequence";
        public override string RosMessageName => k_RosMessageName;

        public int cmd_type;
        public int sequence_id;
        public SequenceMsg sequence;

        public ManageSequenceRequest()
        {
            this.cmd_type = 0;
            this.sequence_id = 0;
            this.sequence = new SequenceMsg();
        }

        public ManageSequenceRequest(int cmd_type, int sequence_id, SequenceMsg sequence)
        {
            this.cmd_type = cmd_type;
            this.sequence_id = sequence_id;
            this.sequence = sequence;
        }

        public static ManageSequenceRequest Deserialize(MessageDeserializer deserializer) => new ManageSequenceRequest(deserializer);

        private ManageSequenceRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd_type);
            deserializer.Read(out this.sequence_id);
            this.sequence = SequenceMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd_type);
            serializer.Write(this.sequence_id);
            serializer.Write(this.sequence);
        }

        public override string ToString()
        {
            return "ManageSequenceRequest: " +
            "\ncmd_type: " + cmd_type.ToString() +
            "\nsequence_id: " + sequence_id.ToString() +
            "\nsequence: " + sequence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
