//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ManagePositionRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ManagePosition";
        public override string RosMessageName => k_RosMessageName;

        public int cmd_type;
        public string position_name;
        public PositionMsg position;

        public ManagePositionRequest()
        {
            this.cmd_type = 0;
            this.position_name = "";
            this.position = new PositionMsg();
        }

        public ManagePositionRequest(int cmd_type, string position_name, PositionMsg position)
        {
            this.cmd_type = cmd_type;
            this.position_name = position_name;
            this.position = position;
        }

        public static ManagePositionRequest Deserialize(MessageDeserializer deserializer) => new ManagePositionRequest(deserializer);

        private ManagePositionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd_type);
            deserializer.Read(out this.position_name);
            this.position = PositionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd_type);
            serializer.Write(this.position_name);
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "ManagePositionRequest: " +
            "\ncmd_type: " + cmd_type.ToString() +
            "\nposition_name: " + position_name.ToString() +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
