//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ManageTrajectoryRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ManageTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public int cmd_type;
        public int trajectory_id;
        public TrajectoryMsg trajectory;

        public ManageTrajectoryRequest()
        {
            this.cmd_type = 0;
            this.trajectory_id = 0;
            this.trajectory = new TrajectoryMsg();
        }

        public ManageTrajectoryRequest(int cmd_type, int trajectory_id, TrajectoryMsg trajectory)
        {
            this.cmd_type = cmd_type;
            this.trajectory_id = trajectory_id;
            this.trajectory = trajectory;
        }

        public static ManageTrajectoryRequest Deserialize(MessageDeserializer deserializer) => new ManageTrajectoryRequest(deserializer);

        private ManageTrajectoryRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.cmd_type);
            deserializer.Read(out this.trajectory_id);
            this.trajectory = TrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd_type);
            serializer.Write(this.trajectory_id);
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "ManageTrajectoryRequest: " +
            "\ncmd_type: " + cmd_type.ToString() +
            "\ntrajectory_id: " + trajectory_id.ToString() +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
