//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ManageTrajectoryResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ManageTrajectory";
        public override string RosMessageName => k_RosMessageName;

        public int status;
        public string message;
        public TrajectoryMsg trajectory;

        public ManageTrajectoryResponse()
        {
            this.status = 0;
            this.message = "";
            this.trajectory = new TrajectoryMsg();
        }

        public ManageTrajectoryResponse(int status, string message, TrajectoryMsg trajectory)
        {
            this.status = status;
            this.message = message;
            this.trajectory = trajectory;
        }

        public static ManageTrajectoryResponse Deserialize(MessageDeserializer deserializer) => new ManageTrajectoryResponse(deserializer);

        private ManageTrajectoryResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.message);
            this.trajectory = TrajectoryMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.message);
            serializer.Write(this.trajectory);
        }

        public override string ToString()
        {
            return "ManageTrajectoryResponse: " +
            "\nstatus: " + status.ToString() +
            "\nmessage: " + message.ToString() +
            "\ntrajectory: " + trajectory.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
