//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ManagePositionResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ManagePosition";
        public override string RosMessageName => k_RosMessageName;

        public int status;
        public string message;
        public PositionMsg position;

        public ManagePositionResponse()
        {
            this.status = 0;
            this.message = "";
            this.position = new PositionMsg();
        }

        public ManagePositionResponse(int status, string message, PositionMsg position)
        {
            this.status = status;
            this.message = message;
            this.position = position;
        }

        public static ManagePositionResponse Deserialize(MessageDeserializer deserializer) => new ManagePositionResponse(deserializer);

        private ManagePositionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.message);
            this.position = PositionMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.message);
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "ManagePositionResponse: " +
            "\nstatus: " + status.ToString() +
            "\nmessage: " + message.ToString() +
            "\nposition: " + position.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
