//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ManageSequenceResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ManageSequence";
        public override string RosMessageName => k_RosMessageName;

        public int status;
        public string message;
        public SequenceMsg sequence;

        public ManageSequenceResponse()
        {
            this.status = 0;
            this.message = "";
            this.sequence = new SequenceMsg();
        }

        public ManageSequenceResponse(int status, string message, SequenceMsg sequence)
        {
            this.status = status;
            this.message = message;
            this.sequence = sequence;
        }

        public static ManageSequenceResponse Deserialize(MessageDeserializer deserializer) => new ManageSequenceResponse(deserializer);

        private ManageSequenceResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            deserializer.Read(out this.message);
            this.sequence = SequenceMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.message);
            serializer.Write(this.sequence);
        }

        public override string ToString()
        {
            return "ManageSequenceResponse: " +
            "\nstatus: " + status.ToString() +
            "\nmessage: " + message.ToString() +
            "\nsequence: " + sequence.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
