//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ObjDetectionResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ObjDetection";
        public override string RosMessageName => k_RosMessageName;

        public int status;
        public const int SUCCESSFUL = 1;
        public const int VIDEO_STREAM_NOT_RUNNING = -1;
        public const int OBJECT_NOT_FOUND = -2;
        public const int MARKERS_NOT_FOUND = -3;
        public ObjectPoseMsg obj_pose;
        public string obj_type;
        public string obj_color;
        public Sensor.CompressedImageMsg img;

        public ObjDetectionResponse()
        {
            this.status = 0;
            this.obj_pose = new ObjectPoseMsg();
            this.obj_type = "";
            this.obj_color = "";
            this.img = new Sensor.CompressedImageMsg();
        }

        public ObjDetectionResponse(int status, ObjectPoseMsg obj_pose, string obj_type, string obj_color, Sensor.CompressedImageMsg img)
        {
            this.status = status;
            this.obj_pose = obj_pose;
            this.obj_type = obj_type;
            this.obj_color = obj_color;
            this.img = img;
        }

        public static ObjDetectionResponse Deserialize(MessageDeserializer deserializer) => new ObjDetectionResponse(deserializer);

        private ObjDetectionResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.status);
            this.obj_pose = ObjectPoseMsg.Deserialize(deserializer);
            deserializer.Read(out this.obj_type);
            deserializer.Read(out this.obj_color);
            this.img = Sensor.CompressedImageMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.status);
            serializer.Write(this.obj_pose);
            serializer.Write(this.obj_type);
            serializer.Write(this.obj_color);
            serializer.Write(this.img);
        }

        public override string ToString()
        {
            return "ObjDetectionResponse: " +
            "\nstatus: " + status.ToString() +
            "\nobj_pose: " + obj_pose.ToString() +
            "\nobj_type: " + obj_type.ToString() +
            "\nobj_color: " + obj_color.ToString() +
            "\nimg: " + img.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
