//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class ObjDetectionRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/ObjDetection";
        public override string RosMessageName => k_RosMessageName;

        public string obj_type;
        public string obj_color;
        public float workspace_ratio;
        public bool ret_image;

        public ObjDetectionRequest()
        {
            this.obj_type = "";
            this.obj_color = "";
            this.workspace_ratio = 0.0f;
            this.ret_image = false;
        }

        public ObjDetectionRequest(string obj_type, string obj_color, float workspace_ratio, bool ret_image)
        {
            this.obj_type = obj_type;
            this.obj_color = obj_color;
            this.workspace_ratio = workspace_ratio;
            this.ret_image = ret_image;
        }

        public static ObjDetectionRequest Deserialize(MessageDeserializer deserializer) => new ObjDetectionRequest(deserializer);

        private ObjDetectionRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.obj_type);
            deserializer.Read(out this.obj_color);
            deserializer.Read(out this.workspace_ratio);
            deserializer.Read(out this.ret_image);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.obj_type);
            serializer.Write(this.obj_color);
            serializer.Write(this.workspace_ratio);
            serializer.Write(this.ret_image);
        }

        public override string ToString()
        {
            return "ObjDetectionRequest: " +
            "\nobj_type: " + obj_type.ToString() +
            "\nobj_color: " + obj_color.ToString() +
            "\nworkspace_ratio: " + workspace_ratio.ToString() +
            "\nret_image: " + ret_image.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
