//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class OpenGripperRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/OpenGripper";
        public override string RosMessageName => k_RosMessageName;

        public byte id;
        public short open_position;
        public short open_speed;
        public short open_hold_torque;

        public OpenGripperRequest()
        {
            this.id = 0;
            this.open_position = 0;
            this.open_speed = 0;
            this.open_hold_torque = 0;
        }

        public OpenGripperRequest(byte id, short open_position, short open_speed, short open_hold_torque)
        {
            this.id = id;
            this.open_position = open_position;
            this.open_speed = open_speed;
            this.open_hold_torque = open_hold_torque;
        }

        public static OpenGripperRequest Deserialize(MessageDeserializer deserializer) => new OpenGripperRequest(deserializer);

        private OpenGripperRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.open_position);
            deserializer.Read(out this.open_speed);
            deserializer.Read(out this.open_hold_torque);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.open_position);
            serializer.Write(this.open_speed);
            serializer.Write(this.open_hold_torque);
        }

        public override string ToString()
        {
            return "OpenGripperRequest: " +
            "\nid: " + id.ToString() +
            "\nopen_position: " + open_position.ToString() +
            "\nopen_speed: " + open_speed.ToString() +
            "\nopen_hold_torque: " + open_hold_torque.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
