//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class PingDxlToolResponse : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/PingDxlTool";
        public override string RosMessageName => k_RosMessageName;

        public byte state;

        public PingDxlToolResponse()
        {
            this.state = 0;
        }

        public PingDxlToolResponse(byte state)
        {
            this.state = state;
        }

        public static PingDxlToolResponse Deserialize(MessageDeserializer deserializer) => new PingDxlToolResponse(deserializer);

        private PingDxlToolResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "PingDxlToolResponse: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
