//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class PingDxlToolRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/PingDxlTool";
        public override string RosMessageName => k_RosMessageName;

        public byte id;
        public string name;

        public PingDxlToolRequest()
        {
            this.id = 0;
            this.name = "";
        }

        public PingDxlToolRequest(byte id, string name)
        {
            this.id = id;
            this.name = name;
        }

        public static PingDxlToolRequest Deserialize(MessageDeserializer deserializer) => new PingDxlToolRequest(deserializer);

        private PingDxlToolRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "PingDxlToolRequest: " +
            "\nid: " + id.ToString() +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
