//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class PullAirVacuumPumpRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/PullAirVacuumPump";
        public override string RosMessageName => k_RosMessageName;

        public byte id;
        public short pull_air_position;
        public short pull_air_hold_torque;

        public PullAirVacuumPumpRequest()
        {
            this.id = 0;
            this.pull_air_position = 0;
            this.pull_air_hold_torque = 0;
        }

        public PullAirVacuumPumpRequest(byte id, short pull_air_position, short pull_air_hold_torque)
        {
            this.id = id;
            this.pull_air_position = pull_air_position;
            this.pull_air_hold_torque = pull_air_hold_torque;
        }

        public static PullAirVacuumPumpRequest Deserialize(MessageDeserializer deserializer) => new PullAirVacuumPumpRequest(deserializer);

        private PullAirVacuumPumpRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.pull_air_position);
            deserializer.Read(out this.pull_air_hold_torque);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.pull_air_position);
            serializer.Write(this.pull_air_hold_torque);
        }

        public override string ToString()
        {
            return "PullAirVacuumPumpRequest: " +
            "\nid: " + id.ToString() +
            "\npull_air_position: " + pull_air_position.ToString() +
            "\npull_air_hold_torque: " + pull_air_hold_torque.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
