//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class RobotMoveRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/RobotMove";
        public override string RosMessageName => k_RosMessageName;

        public RobotMoveCommandMsg cmd;

        public RobotMoveRequest()
        {
            this.cmd = new RobotMoveCommandMsg();
        }

        public RobotMoveRequest(RobotMoveCommandMsg cmd)
        {
            this.cmd = cmd;
        }

        public static RobotMoveRequest Deserialize(MessageDeserializer deserializer) => new RobotMoveRequest(deserializer);

        private RobotMoveRequest(MessageDeserializer deserializer)
        {
            this.cmd = RobotMoveCommandMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.cmd);
        }

        public override string ToString()
        {
            return "RobotMoveRequest: " +
            "\ncmd: " + cmd.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
