//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class SetCalibrationCamRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/SetCalibrationCam";
        public override string RosMessageName => k_RosMessageName;

        public string name;

        public SetCalibrationCamRequest()
        {
            this.name = "";
        }

        public SetCalibrationCamRequest(string name)
        {
            this.name = name;
        }

        public static SetCalibrationCamRequest Deserialize(MessageDeserializer deserializer) => new SetCalibrationCamRequest(deserializer);

        private SetCalibrationCamRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.name);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.name);
        }

        public override string ToString()
        {
            return "SetCalibrationCamRequest: " +
            "\nname: " + name.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
