//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class SetDigitalIORequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/SetDigitalIO";
        public override string RosMessageName => k_RosMessageName;

        public byte pin;
        public byte value;

        public SetDigitalIORequest()
        {
            this.pin = 0;
            this.value = 0;
        }

        public SetDigitalIORequest(byte pin, byte value)
        {
            this.pin = pin;
            this.value = value;
        }

        public static SetDigitalIORequest Deserialize(MessageDeserializer deserializer) => new SetDigitalIORequest(deserializer);

        private SetDigitalIORequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.pin);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pin);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SetDigitalIORequest: " +
            "\npin: " + pin.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
