//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class SetIntRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/SetInt";
        public override string RosMessageName => k_RosMessageName;

        public int value;

        public SetIntRequest()
        {
            this.value = 0;
        }

        public SetIntRequest(int value)
        {
            this.value = value;
        }

        public static SetIntRequest Deserialize(MessageDeserializer deserializer) => new SetIntRequest(deserializer);

        private SetIntRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "SetIntRequest: " +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
