//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class SetLedsRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/SetLeds";
        public override string RosMessageName => k_RosMessageName;

        public int[] values;

        public SetLedsRequest()
        {
            this.values = new int[0];
        }

        public SetLedsRequest(int[] values)
        {
            this.values = values;
        }

        public static SetLedsRequest Deserialize(MessageDeserializer deserializer) => new SetLedsRequest(deserializer);

        private SetLedsRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.values, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.values);
            serializer.Write(this.values);
        }

        public override string ToString()
        {
            return "SetLedsRequest: " +
            "\nvalues: " + System.String.Join(", ", values.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
