//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class SetSequenceAutorunRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/SetSequenceAutorun";
        public override string RosMessageName => k_RosMessageName;

        public bool enable;
        public int mode;
        public int[] sequence_ids;

        public SetSequenceAutorunRequest()
        {
            this.enable = false;
            this.mode = 0;
            this.sequence_ids = new int[0];
        }

        public SetSequenceAutorunRequest(bool enable, int mode, int[] sequence_ids)
        {
            this.enable = enable;
            this.mode = mode;
            this.sequence_ids = sequence_ids;
        }

        public static SetSequenceAutorunRequest Deserialize(MessageDeserializer deserializer) => new SetSequenceAutorunRequest(deserializer);

        private SetSequenceAutorunRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.enable);
            deserializer.Read(out this.mode);
            deserializer.Read(out this.sequence_ids, sizeof(int), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.enable);
            serializer.Write(this.mode);
            serializer.WriteLength(this.sequence_ids);
            serializer.Write(this.sequence_ids);
        }

        public override string ToString()
        {
            return "SetSequenceAutorunRequest: " +
            "\nenable: " + enable.ToString() +
            "\nmode: " + mode.ToString() +
            "\nsequence_ids: " + System.String.Join(", ", sequence_ids.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
