//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class TakePictureRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/TakePicture";
        public override string RosMessageName => k_RosMessageName;

        public string path;

        public TakePictureRequest()
        {
            this.path = "";
        }

        public TakePictureRequest(string path)
        {
            this.path = path;
        }

        public static TakePictureRequest Deserialize(MessageDeserializer deserializer) => new TakePictureRequest(deserializer);

        private TakePictureRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.path);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.path);
        }

        public override string ToString()
        {
            return "TakePictureRequest: " +
            "\npath: " + path.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
