//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class UpdateConveyorIdRequest : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/UpdateConveyorId";
        public override string RosMessageName => k_RosMessageName;

        public byte old_id;
        public byte new_id;

        public UpdateConveyorIdRequest()
        {
            this.old_id = 0;
            this.new_id = 0;
        }

        public UpdateConveyorIdRequest(byte old_id, byte new_id)
        {
            this.old_id = old_id;
            this.new_id = new_id;
        }

        public static UpdateConveyorIdRequest Deserialize(MessageDeserializer deserializer) => new UpdateConveyorIdRequest(deserializer);

        private UpdateConveyorIdRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.old_id);
            deserializer.Read(out this.new_id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.old_id);
            serializer.Write(this.new_id);
        }

        public override string ToString()
        {
            return "UpdateConveyorIdRequest: " +
            "\nold_id: " + old_id.ToString() +
            "\nnew_id: " + new_id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
