//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class JoystickJointsFeedback : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/JoystickJoints";
        public override string RosMessageName => k_RosMessageName;

        //  feedback 
        public bool is_in_joints_limit;

        public JoystickJointsFeedback()
        {
            this.is_in_joints_limit = false;
        }

        public JoystickJointsFeedback(bool is_in_joints_limit)
        {
            this.is_in_joints_limit = is_in_joints_limit;
        }

        public static JoystickJointsFeedback Deserialize(MessageDeserializer deserializer) => new JoystickJointsFeedback(deserializer);

        private JoystickJointsFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.is_in_joints_limit);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.is_in_joints_limit);
        }

        public override string ToString()
        {
            return "JoystickJointsFeedback: " +
            "\nis_in_joints_limit: " + is_in_joints_limit.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
