//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.NiryoOne
{
    [Serializable]
    public class RobotMoveFeedback : Message
    {
        public const string k_RosMessageName = "niryo_one_msgs/RobotMove";
        public override string RosMessageName => k_RosMessageName;

        //  feedback
        public RobotStateMsg state;

        public RobotMoveFeedback()
        {
            this.state = new RobotStateMsg();
        }

        public RobotMoveFeedback(RobotStateMsg state)
        {
            this.state = state;
        }

        public static RobotMoveFeedback Deserialize(MessageDeserializer deserializer) => new RobotMoveFeedback(deserializer);

        private RobotMoveFeedback(MessageDeserializer deserializer)
        {
            this.state = RobotStateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "RobotMoveFeedback: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
